export type CategoryIconGroup = 'All' | 'Hardware' | 'Gaming' | 'Devices' | 'General';

export interface CategoryIconOption {
  key: string;
  label: string;
  iconClass: string;
  group: Exclude<CategoryIconGroup, 'All'>;
  keywords: string[];
}

export const CATEGORY_ICON_FALLBACK = 'fa-solid fa-box-open';

export const CATEGORY_ICON_REGISTRY: CategoryIconOption[] = [
  { key: 'cpu', label: 'CPU', iconClass: 'fa-solid fa-microchip', group: 'Hardware', keywords: ['cpu', 'chip', 'processor', 'intel', 'amd'] },
  { key: 'ram', label: 'RAM', iconClass: 'fa-solid fa-memory', group: 'Hardware', keywords: ['ram', 'memory', 'ddr4', 'ddr5'] },
  { key: 'ssd', label: 'SSD', iconClass: 'fa-solid fa-hard-drive', group: 'Hardware', keywords: ['ssd', 'hdd', 'storage', 'nvme'] },
  { key: 'mainboard', label: 'Mainboard', iconClass: 'fa-solid fa-server', group: 'Hardware', keywords: ['mainboard', 'motherboard', 'board'] },
  { key: 'gpu', label: 'VGA / GPU', iconClass: 'fa-solid fa-display', group: 'Hardware', keywords: ['gpu', 'vga', 'card man hinh', 'graphics'] },
  { key: 'psu', label: 'Nguồn PSU', iconClass: 'fa-solid fa-power-off', group: 'Hardware', keywords: ['psu', 'nguon', 'power'] },
  { key: 'cooling-fan', label: 'Quạt tản nhiệt', iconClass: 'fa-solid fa-fan', group: 'Hardware', keywords: ['fan', 'cooling', 'tan nhiet'] },
  { key: 'liquid-cooling', label: 'Tản nhiệt nước', iconClass: 'fa-solid fa-droplet', group: 'Hardware', keywords: ['aio', 'water cooling', 'tan nhiet nuoc'] },
  { key: 'case', label: 'Case PC', iconClass: 'fa-solid fa-computer', group: 'Hardware', keywords: ['case', 'vo may', 'cay pc'] },
  { key: 'chipset', label: 'Chipset', iconClass: 'fa-solid fa-diagram-project', group: 'Hardware', keywords: ['chipset', 'controller'] },
  { key: 'cable', label: 'Dây cáp', iconClass: 'fa-solid fa-plug', group: 'Hardware', keywords: ['cable', 'cap', 'plug'] },
  { key: 'ethernet', label: 'Card mạng', iconClass: 'fa-solid fa-network-wired', group: 'Hardware', keywords: ['network', 'lan', 'ethernet'] },
  { key: 'wifi', label: 'WiFi', iconClass: 'fa-solid fa-wifi', group: 'Hardware', keywords: ['wifi', 'router', 'internet'] },
  { key: 'battery', label: 'Pin', iconClass: 'fa-solid fa-battery-full', group: 'Hardware', keywords: ['battery', 'pin'] },
  { key: 'charging', label: 'Sạc', iconClass: 'fa-solid fa-charging-station', group: 'Hardware', keywords: ['charger', 'sac', 'adapter'] },
  { key: 'usb', label: 'USB', iconClass: 'fa-brands fa-usb', group: 'Hardware', keywords: ['usb', 'type c', 'hub'] },
  { key: 'sd-card', label: 'Thẻ nhớ', iconClass: 'fa-solid fa-sd-card', group: 'Hardware', keywords: ['sd card', 'the nho'] },
  { key: 'sim-card', label: 'Sim', iconClass: 'fa-solid fa-sim-card', group: 'Hardware', keywords: ['sim', '4g', '5g'] },
  { key: 'database', label: 'Lưu trữ', iconClass: 'fa-solid fa-database', group: 'Hardware', keywords: ['database', 'storage'] },
  { key: 'compact-disc', label: 'Ổ đĩa', iconClass: 'fa-solid fa-compact-disc', group: 'Hardware', keywords: ['cd', 'dvd', 'disc'] },
  { key: 'screwdriver', label: 'Dụng cụ', iconClass: 'fa-solid fa-screwdriver-wrench', group: 'Hardware', keywords: ['tool', 'repair', 'sua chua'] },
  { key: 'gear', label: 'Linh kiện', iconClass: 'fa-solid fa-gear', group: 'Hardware', keywords: ['gear', 'parts', 'linh kien'] },
  { key: 'gears', label: 'Bộ linh kiện', iconClass: 'fa-solid fa-gears', group: 'Hardware', keywords: ['parts', 'config'] },
  { key: 'temperature', label: 'Nhiệt độ', iconClass: 'fa-solid fa-temperature-half', group: 'Hardware', keywords: ['temperature', 'nhiet do'] },
  { key: 'gauge', label: 'Hiệu năng', iconClass: 'fa-solid fa-gauge-high', group: 'Hardware', keywords: ['performance', 'toc do'] },
  { key: 'laptop', label: 'Laptop', iconClass: 'fa-solid fa-laptop', group: 'Devices', keywords: ['laptop', 'notebook', 'may tinh xach tay'] },
  { key: 'laptop-code', label: 'Laptop lập trình', iconClass: 'fa-solid fa-laptop-code', group: 'Devices', keywords: ['developer', 'code', 'lap trinh'] },
  { key: 'desktop', label: 'Desktop', iconClass: 'fa-solid fa-desktop', group: 'Devices', keywords: ['desktop', 'pc', 'may ban'] },
  { key: 'monitor', label: 'Màn hình', iconClass: 'fa-solid fa-tv', group: 'Devices', keywords: ['monitor', 'screen', 'man hinh'] },
  { key: 'mobile', label: 'Điện thoại', iconClass: 'fa-solid fa-mobile-screen-button', group: 'Devices', keywords: ['mobile', 'phone', 'dien thoai'] },
  { key: 'tablet', label: 'Tablet', iconClass: 'fa-solid fa-tablet-screen-button', group: 'Devices', keywords: ['tablet', 'ipad'] },
  { key: 'printer', label: 'Máy in', iconClass: 'fa-solid fa-print', group: 'Devices', keywords: ['printer', 'may in'] },
  { key: 'camera', label: 'Camera', iconClass: 'fa-solid fa-camera', group: 'Devices', keywords: ['camera', 'webcam'] },
  { key: 'webcam', label: 'Webcam', iconClass: 'fa-solid fa-video', group: 'Devices', keywords: ['webcam', 'video'] },
  { key: 'server', label: 'Server', iconClass: 'fa-solid fa-server', group: 'Devices', keywords: ['server', 'may chu'] },
  { key: 'router', label: 'Router', iconClass: 'fa-solid fa-router', group: 'Devices', keywords: ['router', 'wifi'] },
  { key: 'watch', label: 'Smartwatch', iconClass: 'fa-solid fa-clock', group: 'Devices', keywords: ['watch', 'dong ho'] },
  { key: 'headphones-device', label: 'Tai nghe', iconClass: 'fa-solid fa-headphones', group: 'Devices', keywords: ['headphones', 'tai nghe'] },
  { key: 'speaker', label: 'Loa', iconClass: 'fa-solid fa-volume-high', group: 'Devices', keywords: ['speaker', 'loa', 'audio'] },
  { key: 'microphone-device', label: 'Microphone', iconClass: 'fa-solid fa-microphone', group: 'Devices', keywords: ['microphone', 'mic'] },
  { key: 'keyboard-device', label: 'Bàn phím', iconClass: 'fa-solid fa-keyboard', group: 'Devices', keywords: ['keyboard', 'ban phim'] },
  { key: 'mouse-device', label: 'Chuột', iconClass: 'fa-solid fa-computer-mouse', group: 'Devices', keywords: ['mouse', 'chuot'] },
  { key: 'projector', label: 'Máy chiếu', iconClass: 'fa-solid fa-chalkboard', group: 'Devices', keywords: ['projector', 'may chieu'] },
  { key: 'barcode', label: 'Máy quét mã', iconClass: 'fa-solid fa-barcode', group: 'Devices', keywords: ['barcode', 'scanner'] },
  { key: 'vr-device', label: 'Kính VR', iconClass: 'fa-solid fa-vr-cardboard', group: 'Devices', keywords: ['vr', 'virtual reality'] },
  { key: 'satellite', label: 'Thiết bị mạng', iconClass: 'fa-solid fa-satellite-dish', group: 'Devices', keywords: ['network', 'mang'] },
  { key: 'gamepad', label: 'Tay cầm game', iconClass: 'fa-solid fa-gamepad', group: 'Gaming', keywords: ['gamepad', 'controller', 'tay cam'] },
  { key: 'keyboard-gaming', label: 'Bàn phím gaming', iconClass: 'fa-solid fa-keyboard', group: 'Gaming', keywords: ['keyboard', 'gaming', 'ban phim co'] },
  { key: 'mouse-gaming', label: 'Chuột gaming', iconClass: 'fa-solid fa-computer-mouse', group: 'Gaming', keywords: ['mouse', 'gaming', 'chuot'] },
  { key: 'headset-gaming', label: 'Headset gaming', iconClass: 'fa-solid fa-headset', group: 'Gaming', keywords: ['headset', 'gaming', 'tai nghe'] },
  { key: 'chair-gaming', label: 'Ghế gaming', iconClass: 'fa-solid fa-chair', group: 'Gaming', keywords: ['chair', 'ghe gaming'] },
  { key: 'trophy', label: 'Esports', iconClass: 'fa-solid fa-trophy', group: 'Gaming', keywords: ['esports', 'trophy', 'cup'] },
  { key: 'fire', label: 'Hot gaming', iconClass: 'fa-solid fa-fire', group: 'Gaming', keywords: ['hot', 'fire', 'gaming'] },
  { key: 'dragon', label: 'Rồng gaming', iconClass: 'fa-solid fa-dragon', group: 'Gaming', keywords: ['dragon', 'msi', 'gaming'] },
  { key: 'ghost', label: 'Ghost gaming', iconClass: 'fa-solid fa-ghost', group: 'Gaming', keywords: ['ghost', 'gaming'] },
  { key: 'playstation', label: 'PlayStation', iconClass: 'fa-brands fa-playstation', group: 'Gaming', keywords: ['playstation', 'ps5', 'sony'] },
  { key: 'xbox', label: 'Xbox', iconClass: 'fa-brands fa-xbox', group: 'Gaming', keywords: ['xbox', 'console'] },
  { key: 'steam', label: 'Steam', iconClass: 'fa-brands fa-steam', group: 'Gaming', keywords: ['steam', 'game'] },
  { key: 'discord', label: 'Discord', iconClass: 'fa-brands fa-discord', group: 'Gaming', keywords: ['discord', 'community'] },
  { key: 'dice', label: 'Game casual', iconClass: 'fa-solid fa-dice', group: 'Gaming', keywords: ['dice', 'game'] },
  { key: 'rocket', label: 'Tăng tốc', iconClass: 'fa-solid fa-rocket', group: 'Gaming', keywords: ['rocket', 'boost'] },
  { key: 'bolt-gaming', label: 'Tốc độ', iconClass: 'fa-solid fa-bolt', group: 'Gaming', keywords: ['speed', 'bolt'] },
  { key: 'skull', label: 'Hardcore', iconClass: 'fa-solid fa-skull', group: 'Gaming', keywords: ['hardcore', 'game'] },
  { key: 'wand', label: 'RGB effect', iconClass: 'fa-solid fa-wand-magic-sparkles', group: 'Gaming', keywords: ['rgb', 'effect'] },
  { key: 'star-gaming', label: 'Top game', iconClass: 'fa-solid fa-star', group: 'Gaming', keywords: ['top', 'rating'] },
  { key: 'crown-gaming', label: 'Premium gaming', iconClass: 'fa-solid fa-crown', group: 'Gaming', keywords: ['premium', 'vip'] },
  { key: 'shield-gaming', label: 'Gaming bảo hành', iconClass: 'fa-solid fa-shield-halved', group: 'Gaming', keywords: ['warranty', 'gaming'] },
  { key: 'bluetooth', label: 'Bluetooth', iconClass: 'fa-brands fa-bluetooth', group: 'Gaming', keywords: ['bluetooth', 'wireless'] },
  { key: 'wifi-gaming', label: 'Wireless gaming', iconClass: 'fa-solid fa-wifi', group: 'Gaming', keywords: ['wireless', 'wifi'] },
  { key: 'ranking', label: 'Xếp hạng', iconClass: 'fa-solid fa-ranking-star', group: 'Gaming', keywords: ['ranking', 'rank'] },
  { key: 'package', label: 'Package', iconClass: 'fa-solid fa-box-open', group: 'General', keywords: ['box', 'package', 'fallback'] },
  { key: 'box', label: 'Hộp hàng', iconClass: 'fa-solid fa-box', group: 'General', keywords: ['box', 'hop hang'] },
  { key: 'tag', label: 'Thẻ', iconClass: 'fa-solid fa-tag', group: 'General', keywords: ['tag', 'category'] },
  { key: 'tags', label: 'Nhiều thẻ', iconClass: 'fa-solid fa-tags', group: 'General', keywords: ['tags', 'category'] },
  { key: 'cart', label: 'Giỏ hàng', iconClass: 'fa-solid fa-cart-shopping', group: 'General', keywords: ['cart', 'gio hang'] },
  { key: 'bag', label: 'Túi hàng', iconClass: 'fa-solid fa-bag-shopping', group: 'General', keywords: ['shopping', 'bag'] },
  { key: 'truck', label: 'Giao hàng', iconClass: 'fa-solid fa-truck-fast', group: 'General', keywords: ['shipping', 'delivery', 'giao hang'] },
  { key: 'gift', label: 'Quà tặng', iconClass: 'fa-solid fa-gift', group: 'General', keywords: ['gift', 'qua tang'] },
  { key: 'percent', label: 'Khuyến mãi', iconClass: 'fa-solid fa-percent', group: 'General', keywords: ['sale', 'discount'] },
  { key: 'coupon', label: 'Voucher', iconClass: 'fa-solid fa-ticket', group: 'General', keywords: ['coupon', 'voucher'] },
  { key: 'money', label: 'Giá tốt', iconClass: 'fa-solid fa-money-bill-wave', group: 'General', keywords: ['money', 'price'] },
  { key: 'credit-card', label: 'Thanh toán', iconClass: 'fa-solid fa-credit-card', group: 'General', keywords: ['payment', 'card'] },
  { key: 'shield', label: 'Bảo hành', iconClass: 'fa-solid fa-shield-halved', group: 'General', keywords: ['shield', 'warranty'] },
  { key: 'check', label: 'Đã xác thực', iconClass: 'fa-solid fa-circle-check', group: 'General', keywords: ['check', 'verified'] },
  { key: 'star', label: 'Nổi bật', iconClass: 'fa-solid fa-star', group: 'General', keywords: ['featured', 'star'] },
  { key: 'heart', label: 'Yêu thích', iconClass: 'fa-solid fa-heart', group: 'General', keywords: ['wishlist', 'heart'] },
  { key: 'clock', label: 'Thời gian', iconClass: 'fa-solid fa-clock', group: 'General', keywords: ['time', 'clock'] },
  { key: 'calendar', label: 'Lịch', iconClass: 'fa-solid fa-calendar-days', group: 'General', keywords: ['calendar', 'date'] },
  { key: 'newspaper', label: 'Tin tức', iconClass: 'fa-solid fa-newspaper', group: 'General', keywords: ['news', 'blog'] },
  { key: 'image', label: 'Hình ảnh', iconClass: 'fa-solid fa-image', group: 'General', keywords: ['image', 'banner'] },
  { key: 'sliders', label: 'Cấu hình', iconClass: 'fa-solid fa-sliders', group: 'General', keywords: ['settings', 'config'] },
  { key: 'search', label: 'Tìm kiếm', iconClass: 'fa-solid fa-magnifying-glass', group: 'General', keywords: ['search', 'find'] },
  { key: 'filter', label: 'Bộ lọc', iconClass: 'fa-solid fa-filter', group: 'General', keywords: ['filter', 'loc'] },
  { key: 'bars', label: 'Menu', iconClass: 'fa-solid fa-bars', group: 'General', keywords: ['menu', 'bars'] },
  { key: 'grid', label: 'Lưới', iconClass: 'fa-solid fa-border-all', group: 'General', keywords: ['grid', 'layout'] },
  { key: 'list', label: 'Danh sách', iconClass: 'fa-solid fa-list', group: 'General', keywords: ['list', 'danh sach'] },
  { key: 'home', label: 'Trang chủ', iconClass: 'fa-solid fa-house', group: 'General', keywords: ['home', 'trang chu'] },
  { key: 'store', label: 'Cửa hàng', iconClass: 'fa-solid fa-store', group: 'General', keywords: ['store', 'shop'] },
  { key: 'warehouse', label: 'Kho hàng', iconClass: 'fa-solid fa-warehouse', group: 'General', keywords: ['warehouse', 'stock'] },
  { key: 'users', label: 'Khách hàng', iconClass: 'fa-solid fa-users', group: 'General', keywords: ['users', 'customer'] },
  { key: 'user', label: 'Tài khoản', iconClass: 'fa-solid fa-user', group: 'General', keywords: ['user', 'account'] },
  { key: 'phone', label: 'Hotline', iconClass: 'fa-solid fa-phone', group: 'General', keywords: ['phone', 'hotline'] },
  { key: 'email', label: 'Email', iconClass: 'fa-solid fa-envelope', group: 'General', keywords: ['email', 'mail'] },
  { key: 'location', label: 'Địa điểm', iconClass: 'fa-solid fa-location-dot', group: 'General', keywords: ['location', 'address'] },
  { key: 'map', label: 'Bản đồ', iconClass: 'fa-solid fa-map-location-dot', group: 'General', keywords: ['map', 'address'] },
  { key: 'info', label: 'Thông tin', iconClass: 'fa-solid fa-circle-info', group: 'General', keywords: ['info', 'help'] },
  { key: 'support', label: 'Hỗ trợ', iconClass: 'fa-solid fa-headset', group: 'General', keywords: ['support', 'help'] },
  { key: 'toolbox', label: 'Kỹ thuật', iconClass: 'fa-solid fa-toolbox', group: 'General', keywords: ['support', 'technical'] },
  { key: 'award', label: 'Chứng nhận', iconClass: 'fa-solid fa-award', group: 'General', keywords: ['award', 'certified'] },
  { key: 'medal', label: 'Huy chương', iconClass: 'fa-solid fa-medal', group: 'General', keywords: ['medal', 'quality'] },
  { key: 'thumbs-up', label: 'Tin cậy', iconClass: 'fa-solid fa-thumbs-up', group: 'General', keywords: ['trust', 'like'] },
  { key: 'recycle', label: 'Đổi trả', iconClass: 'fa-solid fa-rotate-left', group: 'General', keywords: ['return', 'doi tra'] },
  { key: 'lock', label: 'An toàn', iconClass: 'fa-solid fa-lock', group: 'General', keywords: ['secure', 'safe'] },
  { key: 'unlock', label: 'Mở khóa', iconClass: 'fa-solid fa-unlock', group: 'General', keywords: ['unlock'] },
  { key: 'download', label: 'Tải xuống', iconClass: 'fa-solid fa-download', group: 'General', keywords: ['download'] },
  { key: 'upload', label: 'Tải lên', iconClass: 'fa-solid fa-upload', group: 'General', keywords: ['upload'] },
  { key: 'cloud', label: 'Cloud', iconClass: 'fa-solid fa-cloud', group: 'General', keywords: ['cloud'] },
  { key: 'globe', label: 'Toàn cầu', iconClass: 'fa-solid fa-globe', group: 'General', keywords: ['global', 'world'] },
  { key: 'lightbulb', label: 'Ý tưởng', iconClass: 'fa-solid fa-lightbulb', group: 'General', keywords: ['idea', 'tip'] },
  { key: 'bell', label: 'Thông báo', iconClass: 'fa-solid fa-bell', group: 'General', keywords: ['notification'] },
  { key: 'flag', label: 'Cờ', iconClass: 'fa-solid fa-flag', group: 'General', keywords: ['flag'] },
  { key: 'bookmark', label: 'Lưu lại', iconClass: 'fa-solid fa-bookmark', group: 'General', keywords: ['bookmark', 'save'] },
  { key: 'link', label: 'Liên kết', iconClass: 'fa-solid fa-link', group: 'General', keywords: ['link', 'url'] },
  { key: 'bolt', label: 'Nhanh', iconClass: 'fa-solid fa-bolt', group: 'General', keywords: ['fast', 'speed'] },
  { key: 'sparkles', label: 'Mới', iconClass: 'fa-solid fa-wand-magic-sparkles', group: 'General', keywords: ['new', 'sparkle'] },
  { key: 'fire-sale', label: 'Flash sale', iconClass: 'fa-solid fa-fire-flame-curved', group: 'General', keywords: ['flash sale', 'hot sale'] },
  { key: 'chart', label: 'Thống kê', iconClass: 'fa-solid fa-chart-line', group: 'General', keywords: ['chart', 'analytics'] },
  { key: 'bars-progress', label: 'Tiến trình', iconClass: 'fa-solid fa-bars-progress', group: 'General', keywords: ['progress', 'status'] },
  { key: 'circle-plus', label: 'Thêm mới', iconClass: 'fa-solid fa-circle-plus', group: 'General', keywords: ['add', 'plus'] }
];

export function isValidCategoryIcon(icon?: string): boolean {
  return !!icon && CATEGORY_ICON_REGISTRY.some(item => item.iconClass === icon);
}

export function resolveCategoryIcon(icon?: string, categoryName?: string, categorySlug?: string): string {
  const normalizedName = categoryName?.trim().toLowerCase();
  const normalizedSlug = categorySlug?.trim().toLowerCase();
  if (normalizedName === 'cpu' || normalizedSlug === 'cpu' || normalizedSlug?.startsWith('cpu-')) {
    return 'fa-solid fa-microchip';
  }
  return isValidCategoryIcon(icon) ? icon! : CATEGORY_ICON_FALLBACK;
}
